const mongoose=require('mongoose');
const Schema=mongoose.Schema;
const Std=new Schema({
    name:{
        type:String,
        required:true,
        trim:true,
        minlength:1
    },
    centre:{
        type:String
    },
    mobile:{
        type:Number,
    },
    alternate_mobile:{
        type:Number
    },
    father_name:{
        type:String
    },
    father_mobile:{
        type:Number,
    },
    address:{
        type:String
    },
    email:{
        type:String,
    },
    college:{
        type:String
    },
    package_opted:{
        type:String,
        default:null
    },
    individual_courses:[{
        type:String,
        default:null
    }],
    centre:{
        type:String,
        required:true
    },
    installments:[{
        type:String
    }],
    total_fee:{
        type:Number,
    },
    fee_paid:{
        type:Number,
    },
    fee_due:{
        type:Number,
        default:0
    },
    pay_date:[
        {
            type:Date
        }
    ],
    last_due:{
        type:Date
    },
    due_date:[{
        type:Date
    }],
    registration_date:{
        type:Date
    },
    comments:{
        type:String,
        default:null
    },
});
var Student=mongoose.model('student',Std);
module.exports={
    Student:Student
};